### PR TITLE
#August2018Release1

### PR DESCRIPTION
**Pull request by namrataukirde**
Hi Team,

This PR contains changes for:

- Ember upgrade to 2.13 (GCW-2021)
- Xcode upgrade to 9.2 (GCW-1996)

Please Review.

Thanks.

### CODE REVIEW

**Comment by Darshan-Chauhan** [comment]
@namrataukirde , are we releasing this??

**Comment by namrataukirde** [comment]
@Darshan-Chauhan, We will check the status of tickets today then we can decide about a release. Thanks :)

**Comment by Darshan-Chauhan** [comment]
This PR has dependency on CI 2.0 migrate as it'll fix android upgrade issue of licence agreement.

CC: @namrataukirde

**Comment by steveyken** [comment]
Closing and re-opening a new PR with the full set of changes

**Pull request closed without merging**
